# Generated by Django 5.1.2 on 2024-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
